@startuml Sequencia
skinparam style strictuml
autoactivate on

actor Alocador
participant Tela as t
participant Controlador as c
' participant Prédio as p
participant Sala as s
' participant Alocação as a
' participant Alocação as a2
participant "Gerenciador de Salas" as gs
participant Sala as s

Alocador -> t : solicita listagem de todas as salas
    t -> c : getAllSalas()
        c -> gs : getAllSalas()
            return sala[]
    return sala[]
return 

Alocador -> t : solicita criação de nova sala
    t -> c : criarSala(sala)
        c -> gs : criarSala(sala)
        create s
            gs -> s : << create >>
            return 
        return 
    return
return 

Alocador -> t : solicita visualizar sala (s)
    t -> c : getSala(código_sala)
        c -> gs : getSala(codigo_sala)
            return s        
    return s
return 

Alocador -> t : solicita atualizar sala (s)
    t -> c : atualizarSala(código_sala, sala)
        c -> gs : getSala(codigo_sala)
            return s
        c -> s : setSala(sala)
            return 
        return 
    return

Alocador -> t : solicita deletar sala (s)
    t -> c : deletarSala(código_sala)
        c -> gs : deletarSala(código_sala)
            return 
        return 
    return

@enduml