@startuml Sequencia
skinparam style strictuml
autoactivate on

actor Alocador
participant Tela as t
participant Controlador as c
' participant Prédio as p
' participant Sala as s
' participant Alocação as a
' participant Alocação as a2
participant "Gerenciafor de Disciplinas" as gd
participant Disciplina as d
participant Turma as tu

Alocador -> t : solicita listagem de todas as turmas
    t -> c : getAllTurmas()
        c -> gd : getAllDisciplinas()
            return disciplina[]
            loop para cada disciplina
                c -> d : getAllTurmas()
                return turmaDisciplina[]        
            end
    return turmaDisciplinas[]
return 

Alocador -> t : solicita criação de nova turma
    t -> c : criarTurma(código_turma, código_disciplina,\n data_inicio, data_fim, faixa_horário[],\n número_alunos, recorrência, nome_professor,\n necessidade_equipamento, acessibilidade)
        c -> gd : getDisciplina(código_disciplina)
            return d
        c -> d : criarTurma(código_turma,\n data_inicio, data_fim, faixa_horário[],\n número_alunos, recorrência, nome_professor,\n necessidade_equipamento, acessibilidade)
        create tu
            d -> tu : << create >>
            return 
        return 
    return
return 

Alocador -> t : solicita visualizar turma (t)
    t -> c : getTurma(código_turma, código_disciplina)
        c -> gd : getDisciplina()
            return d
        c -> d : getTurma(codigo_turma)
        ' get tu
        '     d -> tu : << get >>
        '     return 
            return t        
    return t
return 


@enduml