@startuml Sequencia
skinparam style strictuml
autoactivate on

actor Alocador
participant Tela as t
participant Controlador as c
participant Prédio as p
participant Sala as s
participant Alocação as a
participant Alocação as a2

Alocador -> t : informa dados da atividade\n(nome, data, horário_inicio, \nhorário_fim e número_participantes)
    t -> c : getSalasCompativeis(número_participantes)
        c -> p : getSalasCompatíveis\n(número_de_participantes)
            return s[]
        loop para cada sala
        c -> s : getConflitoAtividade(data, horário_inicio, horário_fim)
        loop para cada alocação
            s -> a : getConflitoAtividade(data, horário_inicio, horário_fim)
            return existe_conflito
        end
        return existe_pelo_menos_um_conflito
    end
    
return informações
return 

Alocador -> t : escolhe sala (s)
    t -> c : alocarSalaAtividade(s, data, horário_inicio, horário_fim)
    
    c -> s : alocarSalaAtividade(s, data, horário_inicio, horário_fim)
    create a2
        s -> a2 : << create >>
    return 
return 
return
return 
@enduml